### ISSUE TITLE
Conversion of *.d.ts files?

### ISSUE THREAD

**Issue by oleersoy** [LeDDGroup/typescript-transform-paths#1]
Hi - Nice work!
I'm considering putting it to use in:
https://www.npmjs.com/package/@fireflysemantics/slice

Right now I'm creating a dist folder with *.d.ts files and *.js files.  I see that typescript-transform-paths converts the *.js files, but the paths still appear in the *.d.ts files.  Is there a setting that will convert the *.d.ts files as well?

Also right now in the root of the Slice project I have a `createdist.js` script that performs the path conversion.  It uses globby to find the resources and replaces the `path` configured proxies with relative paths.

I tried configuring `typescript-transform-paths` and running `npm compile` (Which compiles to the `target` directory, but it does not look like the paths are being replaced.  Any ideas?

**Comment by danielpa9708** [comment]
Hi @oleersoy, there's an issue https://github.com/LeDDGroup/typescript-transform-paths/issues/2 that probably affect you witch would be fixed in https://github.com/LeDDGroup/typescript-transform-paths/pull/3, I will merge the PR tomorrow if you have any thoughts on it.
Also I checked out your repo https://github.com/fireflysemantics/slice and while you installed *typescript-transform-paths*, you'll have to setup [ttypescript](https://github.com/cevek/ttypescript/) too for your compilation process.

**Comment by oleersoy** [comment]
Hi @danielpa9708 - Super glad to hear it!  Thanks for the heads up on the ttypescript tool.

**Comment by danielpa9708** [comment]
Let me know if you have any other issue
